### ISSUE TITLE
About Flym

### ISSUE THREAD

**Issue by nikhilCad** [FredJul/CardsKnight#1]
Sorry for posting this issue here. But I have some queries about archiving of Flym(will close this issue) : 
1) Has Google only blocked updates of Flym, or do you know of any other RSS readers that have been blocked from updating?
2) Is Feedly also blocked from updating?
3) Can this app continue to publish its latest builds(whenever some contributor adds something) on F-droid and Github Releases only, like Newpipe does?

**Comment by FredJul** [comment]
1. I have no idea about others RSS readers, I suppose they will know the same issue except if Google didn't notice them.
2. same, no idea
3. it is technically possible of course, but I personally have no motivation to do so. Hence I encourage to fork Flym.

**Comment by nikhilCad** [comment]
Thanks for replying. I respect your decision.
